# Welcome to Jekyll!
title: coltivare.wiki
description: Come fare orto biologico, tanti consigli su come coltivare l'orto senza usare prodotti chimici, per ottenere verdure biologiche sane e rispettose dell'ambiente.
baseurl: ""
url: "https://www.coltivare.wiki"

# Build settings
theme: minima
permalink: /:title
plugins:
    - jekyll-sitemap
    - jekyll-minifier

exclude:
    - firebase.json
    - depoly.sh
    - scraper
    - serve.sh

locale: it_IT
