# Welcome to Jekyll!
title: coltivare.wiki
description: Coltivare.wiki è un blog di domande e risposte che nasce dal nostro desiderio di diffondere le buone pratiche dell’agricoltura biologica e non solo.

baseurl: ""
url: "https://www.coltivare.wiki"

# Build settings
theme: minima
permalink: /:title
plugins:
    - jekyll-sitemap
    - jekyll-minifier

exclude:
    - firebase.json
    - depoly.sh
    - scraper
    - serve.sh

locale: it_IT
